# default stuff
name: "Blog&stuff"
markdown: redcarpet
pygments: true
excerpt_separator: "<!-- more -->"
# authors - add a new author like fenix
authors:
    fenix:
        display_name: Francesco Esposito
        email: fraesps@gmail.com
    mrbabbs:
        display_name: Giovanni Esposito
        email: gioesps@gmail.com

# pretty links
permalink: '/:year/:title'

# pagination stuff 
paginate: 3
paginate_path: '/page:num'

# include of new folder "_pages" where we can write our markdown pages
include: ['_pages']

# this is used to follow the permalink var in each page 
relative_permalinks: false

# folder to store post by categories N.B. if it has to be changed look up the "_plugins/categories.rb" file
cat_folder: "/categories/"
